image: registry.gitlab.nxs360.com/docker/php:8.0-cli

include:
    - project: packages/gitlab-templates/ci-cd-template-spryker-composer-package
      ref: main
      file: .gitlab-ci.yml

default:
    before_script:
        - composer config gitlab-token.gitlab.nxs360.com $GITLAB_COMPOSER_USER $GITLAB_COMPOSER_PASS
